apiVersion: apps/v1
kind: Deployment
metadata:
  name: traffmonetizer-node
  labels:
    app: traffmonetizer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: traffmonetizer
  template:
    metadata:
      labels:
        app: traffmonetizer
    spec:
      containers:
      - name: traffmonetizer
        image: docker.io/traffmonetizer/cli_v2:latest
        args: ["start", "accept", "--token", "$(TRAFFMONETIZER_TOKEN)"]
        env:
        - name: TRAFFMONETIZER_TOKEN
          valueFrom:
            secretKeyRef:
              name: passive-revenue-secrets
              key: TRAFFMONETIZER_TOKEN
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "200m"
